--建立uaop表空间
--uaop_default

CREATE TABLESPACE uaop_default
DATAFILE  'uaop_default.dbf' SIZE 1024 M 
AUTOEXTEND ON 
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 M;

CREATE TEMPORARY TABLESPACE uaop_temporary
TEMPFILE
  'uaop_temp.dbf' SIZE 1024 M 
AUTOEXTEND ON
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 M;

--建立uaop用户
--add user: uaop/uaop

CREATE USER uaop
  IDENTIFIED BY uaop
  DEFAULT TABLESPACE uaop_default
  TEMPORARY TABLESPACE uaop_temporary
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
  GRANT DBA TO uaop;
  GRANT RESOURCE TO uaop;
  ALTER USER uaop DEFAULT ROLE ALL;
  GRANT SELECT ANY TABLE TO uaop;
  GRANT UNLIMITED TABLESPACE TO uaop;
  GRANT CREATE ANY TABLE to uaop;
