
  ALTER TABLE UAOP_SYSUSER add LAST_MODIFY_ACCOUNT    VARCHAR(128);
  ALTER TABLE UAOP_SYSUSER add LAST_TERMINAL      VARCHAR(128);
  ALTER TABLE UAOP_SYSUSER add LAST_SYS           VARCHAR(32);


  ALTER TABLE UAOP_ROLE add TYPE    NUMERIC(3,0) NOT NULL;
  ALTER TABLE UAOP_ROLE add CREATE_ACCOUNT     VARCHAR(128) NOT NULL;
  ALTER TABLE UAOP_ROLE add CREATE_TIME        NUMERIC(20,0) NOT NULL;
  ALTER TABLE UAOP_ROLE add LAST_MODIFY_TIME   NUMERIC(20,0);
  ALTER TABLE UAOP_ROLE add LAST_MODIFY_ACCOUNT     VARCHAR(128);
  ALTER TABLE UAOP_ROLE add LAST_TERMINAL      VARCHAR(128);
  ALTER TABLE UAOP_ROLE add LAST_SYS           VARCHAR(32);


  ALTER TABLE UAOP_USER_INFO add LAST_MODIFY_ACCOUNT     VARCHAR(128);
  ALTER TABLE UAOP_USER_INFO add LAST_TERMINAL      VARCHAR(128);
  ALTER TABLE UAOP_USER_INFO add LAST_SYS           VARCHAR(32);



  ALTER TABLE UAOP_ORGANIZATION add CREATE_ACCOUNT     VARCHAR(128) NOT NULL;
  ALTER TABLE UAOP_ORGANIZATION add CREATE_TIME        NUMERIC(20,0) NOT NULL, 
  ALTER TABLE UAOP_ORGANIZATION add LAST_MODIFY_TIME   NUMERIC(20,0);
  ALTER TABLE UAOP_ORGANIZATION add LAST_MODIFY_ACCOUNT     VARCHAR(128);
  ALTER TABLE UAOP_ORGANIZATION add LAST_TERMINAL      VARCHAR(128);
  ALTER TABLE UAOP_ORGANIZATION add LAST_SYS           VARCHAR(32);
  
  
  ALTER TABLE UAOP_ROLE add TYPE    NUMERIC(3,0);
  ALTER TABLE UAOP_ROLE add CREATE_ACCOUNT     VARCHAR(128);
  ALTER TABLE UAOP_ROLE add CREATE_TIME        NUMERIC(20,0);
  
  update UAOP_ROLE set TYPE = 0;
  update UAOP_ROLE set CREATE_ACCOUNT = 'admin';
  update UAOP_ROLE set CREATE_TIME = '1471562860029';
  
  ALTER TABLE UAOP_ROLE modify TYPE    NUMERIC(3,0) NOT NULL;
  ALTER TABLE UAOP_ROLE modify CREATE_ACCOUNT     VARCHAR(128)  NOT NULL;
  ALTER TABLE UAOP_ROLE modify CREATE_TIME        NUMERIC(20,0) NOT NULL; 
  
  
  ALTER TABLE UAOP_ORGANIZATION add CREATE_ACCOUNT     VARCHAR(128);
  ALTER TABLE UAOP_ORGANIZATION add CREATE_TIME        NUMERIC(20,0);
  
  update UAOP_ORGANIZATION set CREATE_ACCOUNT = 'admin';
  update UAOP_ORGANIZATION set CREATE_TIME = '1471562860029';
  
  ALTER TABLE UAOP_ORGANIZATION modify CREATE_ACCOUNT     VARCHAR(128)  NOT NULL;
  ALTER TABLE UAOP_ORGANIZATION modify CREATE_TIME        NUMERIC(20,0) NOT NULL; 
  
  ALTER TABLE UAOP_SYSUSER modify LAST_MODIFY_TIME   NUMERIC(20,0);
  
  
  
  ALTER TABLE UAOP_USER_INFO add  POST               VARCHAR(64);
  ALTER TABLE UAOP_USER_INFO add  BIRTH              NUMERIC(20,0);
  ALTER TABLE UAOP_USER_INFO add  POLI               VARCHAR(64);
  ALTER TABLE UAOP_USER_INFO add  PHONE              VARCHAR(32);
  ALTER TABLE UAOP_USER_INFO add  FAX                VARCHAR(32);
  ALTER TABLE UAOP_USER_INFO add  ADDRESS            VARCHAR(256);
  ALTER TABLE UAOP_USER_INFO add  ZIPCODE            VARCHAR(32);
  ALTER TABLE UAOP_USER_INFO add  PROVINCE           VARCHAR(64);
  ALTER TABLE UAOP_USER_INFO add  CITY               VARCHAR(64);
  ALTER TABLE UAOP_USER_INFO add  COUNTY             VARCHAR(64);